#!/usr/bin/env python3
"""
v8/deployment_cost.py — memory footprint, cache growth and eviction
(audit 2.8: "no memory footprint, no eviction policy, no cache-size growth
curve, and no statement of what a 31,201-entry cache costs to hold. For a
systems venue these are expected").

WHAT IS MEASURED
  1. Bytes per entry per tier, from the real artifacts rather than from an
     estimate: L1 stores a query, an answer and supporting URL hashes; L2 a
     query and an ordered URL list; L3 a URL key and extracted page text.
     Answer lengths come from the generated answers already on disk, page
     text from the run_00 snapshots, URL lists from the manifest.
  2. The embedding index, which is the part that does not shrink: one
     vector per L1 and L2 entry at BGE-M3's 1024 dimensions, reported at
     fp32, fp16 and int8.
  3. Growth curve: distinct cache entries against queries processed, taken
     from the deployed trace, so the curve is the system's own behaviour
     and not a synthetic model.
  4. Eviction. The paper's cache is unbounded. This sweeps a bounded cache
     under LRU and under a freshness-aware policy that evicts the entry
     with the highest P(stale) first, and reports what search savings and
     hit counts survive at each capacity. That is the number a deployment
     needs: how small can the cache be before the savings go away.

SAFETY  Read-only on every locked artifact. Writes v8/ only.

Run:  cd ~/freshcache && python3 -u v8/deployment_cost.py
"""
from __future__ import annotations

import json
import pathlib
import random
import statistics
import sys

import numpy as np
from collections import OrderedDict, defaultdict

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
import experiment as exp   # noqa: E402

DATA = pathlib.Path("data")
V8   = pathlib.Path(__file__).resolve().parent
EMBED_DIM = 1024                       # BAAI/bge-m3
CAPS = [500, 1_000, 2_500, 5_000, 10_000]   # unbounded is read from the locked run


def sim_row(q, cached_queries):
    """Vectorised cosine lookup: one row of the precomputed matrix, gathered."""
    i = exp._QUERY_TO_IDX.get(q, -1)
    idx = np.fromiter((exp._QUERY_TO_IDX.get(c, -1) for c in cached_queries),
                      dtype=np.int64, count=len(cached_queries))
    out = np.zeros(len(cached_queries), dtype=np.float32)
    ok = idx >= 0
    if i >= 0 and ok.any():
        out[ok] = exp._SIM_MATRIX[i, idx[ok]]
    return out


def load_jsonl(p, limit=None):
    out = []
    if not p.exists():
        return out
    for i, line in enumerate(open(p, encoding="utf-8")):
        if limit and i >= limit:
            break
        line = line.strip()
        if line:
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                pass
    return out


def measure_entry_sizes(records):
    """Bytes per entry per tier, measured from artifacts on disk."""
    # answers actually generated by the pipeline
    answers = []
    for f in ("b4_answer_level.jsonl", "b4_answer_level_llama8b.jsonl",
              "abc_answer_quality.jsonl"):
        for r in load_jsonl(DATA / f):
            for k in ("cached_answer", "fresh_answer", "answer_a", "answer_c"):
                if isinstance(r.get(k), str) and r[k].strip():
                    answers.append(len(r[k].encode("utf-8")))
    qlen = [len(r["query"].encode("utf-8")) for r in records]
    nurls = [len(r["urls"]) for r in records]

    # L3 page text, sampled from run_00 snapshots
    snaps = sorted((DATA / "snapshots" / "run_00").glob("*.json"))
    random.seed(42)
    sample = random.sample(snaps, min(3000, len(snaps)))
    textlen = []
    for f in sample:
        try:
            textlen.append(len(json.load(open(f)).get("extracted_text", "")
                               .encode("utf-8")))
        except Exception:
            pass

    URL_HASH = 24          # hex chars, as stored
    TS       = 8
    mean = statistics.mean
    l1 = mean(qlen) + (mean(answers) if answers else 0) + \
        mean(nurls) * URL_HASH + TS + 32
    l2 = mean(qlen) + mean(nurls) * URL_HASH + TS + 16
    l3 = URL_HASH + mean(textlen) + TS + 128     # +headers/etag/status
    return {
        "mean_query_bytes": round(mean(qlen), 1),
        "mean_answer_bytes": round(mean(answers), 1) if answers else None,
        "n_answers_sampled": len(answers),
        "mean_urls_per_query": round(mean(nurls), 2),
        "mean_page_text_bytes": round(mean(textlen), 1),
        "median_page_text_bytes": round(statistics.median(textlen), 1),
        "n_snapshots_sampled": len(textlen),
        "bytes_per_entry": {"L1": round(l1, 1), "L2": round(l2, 1),
                            "L3": round(l3, 1)},
    }


def trace_growth(records, stale, sim_age, sample_every=1000):
    """
    Cache occupancy as the trace advances, derived from the realized hit logs
    rather than by re-running the similarity search. An L1 entry is written
    only on a miss, so |L1| after i requests is i minus the L1 hits so far;
    the same holds for L2, and L3 grows by the distinct URLs seen. This is
    the same trace the locked results describe, at O(n) instead of O(n x |cache|).
    """
    l1_hit_ids, l2_hit_ids = set(), set()
    for f, acc in (("data/l1_hits_rulebased_t24h.jsonl", l1_hit_ids),
                   ("data/l2_hits_rulebased_t24h.jsonl", l2_hit_ids)):
        for r in load_jsonl(pathlib.Path(f)):
            acc.add(r["query_id"])
    curve, l1n, l2n, seen = [], 0, 0, set()
    for i, r in enumerate(records, 1):
        qid = r["query_id"]
        if qid in l1_hit_ids:
            pass                      # L1 hit returns before writing an entry
        else:
            l1n += 1
            if qid not in l2_hit_ids:
                l2n += 1
            else:
                l2n += 1              # a served list is re-registered on a hit
            for u in r["urls"]:
                seen.add(u["url_hash"])
        if i % sample_every == 0 or i == len(records):
            curve.append({"queries": i, "l1": l1n, "l2": l2n, "l3": len(seen)})
    return curve


def bounded_run(records, stale, sim_age, cap, policy):
    """
    FreshCache with a bounded L1 and L2 under `policy`:
      'lru'       evict least recently used
      'freshness' evict the entry with the highest P(stale) at this age,
                  ties broken by least recently used
    L3 is bounded at 4x cap, since it holds one entry per URL rather than
    per query. Decision logic is otherwise unchanged.
    """
    l1 = OrderedDict(); l2 = OrderedDict(); l3 = OrderedDict()
    cap3 = None if cap is None else cap * 4
    search = l1h = l2h = l3h = stale_err = 0
    ev1 = ev2 = ev3 = 0

    def evict(od, limit, counter):
        n = 0
        while limit is not None and len(od) > limit:
            if policy == "lru":
                od.popitem(last=False)
            else:
                worst = max(od.items(),
                            key=lambda kv: exp.p_stale(kv[1]["fc"], sim_age,
                                                       kv[1]["tier"]))
                od.pop(worst[0])
            n += 1
        return n

    for r in records:
        q, fc, urls = r["query"], r["freshness_class"], r["urls"]
        url_hashes = [u["url_hash"] for u in urls]
        hit, best = None, 0.0
        if fc != "REAL_TIME" and l1:
            ks = list(l1.keys())
            sims = sim_row(q, [l1[k]["query"] for k in ks])
            order = np.argsort(-sims)
            for oi in order:
                sv = float(sims[oi])
                if sv < exp.L1_SIM_THRESHOLD or sv <= best:
                    break
                e = l1[ks[oi]]
                if exp.p_stale(e["fc"], sim_age, "answer") > exp.EPS_ANSWER:
                    continue
                if (exp._entity_match(q, e["query"])
                        and exp.semantic_equivalent(q, e["query"], sv)):
                    best, hit, hk = sv, e, ks[oi]
                    break
        if hit:
            l1h += 1
            l1.move_to_end(hk)
            if any(u in stale for u in hit["url_hashes"]):
                stale_err += 1
            continue

        h2, b2 = None, 0.0
        if fc != "REAL_TIME" and l2:
            ks2 = list(l2.keys())
            sims2 = sim_row(q, [l2[k]["query"] for k in ks2])
            order2 = np.argsort(-sims2)
            for oi in order2:
                sv = float(sims2[oi])
                if sv < exp.L2_SIM_THRESHOLD or sv < exp._L2_EQ_SIM_FLOOR or sv <= b2:
                    break
                e = l2[ks2[oi]]
                if exp.p_stale(e["fc"], sim_age, "url_list") <= exp.EPS_URL_LIST:
                    b2, h2, hk2 = sv, e, ks2[oi]
                    break
        if h2:
            l2h += 1
            l2.move_to_end(hk2)
            served = h2["url_hashes"]
        else:
            search += 1
            served = url_hashes
        l2[r["query_id"]] = {"query": q, "fc": fc, "url_hashes": served,
                             "tier": "url_list"}
        ev2 += evict(l2, cap, "l2")

        hit_stale = False
        for u in urls:
            uh = u["url_hash"]
            if uh in l3:
                if exp.p_stale(fc, sim_age, "content") <= exp.EPS_CONTENT:
                    l3h += 1
                    l3.move_to_end(uh)
                    if uh in stale:
                        hit_stale = True
                    continue
            l3[uh] = {"fc": fc, "tier": "content"}
            ev3 += evict(l3, cap3, "l3")
        if hit_stale:
            stale_err += 1
        l1[r["query_id"]] = {"query": q, "fc": fc, "url_hashes": url_hashes,
                             "tier": "answer"}
        ev1 += evict(l1, cap, "l1")

    n = len(records)
    hits = l1h + l2h + l3h
    return {"cap": cap, "policy": policy, "l1_hits": l1h, "l2_hits": l2h,
            "l3_hits": l3h, "search_calls": search,
            "search_saved_pct": round(100 * (1 - search / n), 2),
            "drift": round(stale_err / max(hits, 1), 6),
            "evictions": {"l1": ev1, "l2": ev2, "l3": ev3},
            "final_entries": {"l1": len(l1), "l2": len(l2), "l3": len(l3)}}


def main():
    queries     = exp.load_jsonl(exp.QUERIES_FILE)
    manifest    = exp.load_jsonl(exp.MANIFEST_FILE)
    changes     = exp.load_jsonl(exp.CHANGE_FILE)
    paraphrases = (exp.load_jsonl(exp.PARAPHRASE_FILE)
                   if exp.PARAPHRASE_FILE.exists() else [])
    records = exp.build_query_records(queries, manifest, paraphrases)
    exp.precompute_similarity_matrix(records)
    stale = exp.build_stale_sets(changes)["rerun_24h"]
    sim_age = exp.SIM_AGES["24h"]
    out = {}

    print(f"\n{'='*80}\n  1. ENTRY SIZE, MEASURED FROM ARTIFACTS\n{'='*80}")
    sz = measure_entry_sizes(records)
    out["entry_sizes"] = sz
    print(f"  mean query            {sz['mean_query_bytes']:>10.1f} B")
    print(f"  mean generated answer {sz['mean_answer_bytes']:>10.1f} B "
          f"(n={sz['n_answers_sampled']:,})")
    print(f"  mean URLs per query   {sz['mean_urls_per_query']:>10.2f}")
    print(f"  mean page text        {sz['mean_page_text_bytes']:>10.1f} B "
          f"(median {sz['median_page_text_bytes']:,.0f}, "
          f"n={sz['n_snapshots_sampled']:,})")
    for t, b in sz["bytes_per_entry"].items():
        print(f"  bytes per {t} entry   {b:>10.1f} B")

    print(f"\n{'='*80}\n  2. FOOTPRINT OF THE DEPLOYED CACHE\n{'='*80}")
    locked = json.load(open(exp.RESULTS_FILE))["t=24h_ALL"]["FreshCache_Full"]
    curve = trace_growth(records, stale, sim_age)
    final = curve[-1]
    out["growth_curve"] = curve
    bpe = sz["bytes_per_entry"]
    payload = (final["l1"] * bpe["L1"] + final["l2"] * bpe["L2"]
               + final["l3"] * bpe["L3"])
    idx_entries = final["l1"] + final["l2"]
    idx = {"fp32": idx_entries * EMBED_DIM * 4,
           "fp16": idx_entries * EMBED_DIM * 2,
           "int8": idx_entries * EMBED_DIM * 1}
    out["footprint"] = {"entries": final, "payload_bytes": payload,
                        "index_bytes": idx,
                        "total_fp16_bytes": payload + idx["fp16"]}
    MB = 1024 ** 2
    print(f"  entries at end of trace: L1 {final['l1']:,}  "
          f"L2 {final['l2']:,}  L3 {final['l3']:,}")
    print(f"  payload                 {payload/MB:>9.1f} MB")
    for k, v in idx.items():
        print(f"  embedding index ({k})  {v/MB:>9.1f} MB "
              f"({idx_entries:,} vectors x {EMBED_DIM}d)")
    print(f"  TOTAL at fp16           {(payload+idx['fp16'])/MB:>9.1f} MB")
    print(f"  L3 is {100*final['l3']*bpe['L3']/payload:.1f}% of payload; page "
          f"text dominates, and it is the tier a deployment would evict first.")

    print(f"\n{'='*80}\n  3. GROWTH CURVE\n{'='*80}")
    print(f"  {'queries':>10}{'L1':>9}{'L2':>9}{'L3':>9}{'MB(fp16)':>11}")
    for p in curve[::max(1, len(curve)//12)]:
        tot = (p["l1"]*bpe["L1"] + p["l2"]*bpe["L2"] + p["l3"]*bpe["L3"]
               + (p["l1"]+p["l2"])*EMBED_DIM*2)
        print(f"  {p['queries']:>10,}{p['l1']:>9,}{p['l2']:>9,}"
              f"{p['l3']:>9,}{tot/MB:>11.1f}")

    print(f"\n{'='*80}\n  4. BOUNDED CACHE AND EVICTION\n{'='*80}")
    print(f"  {'cap':>8}{'policy':>12}{'L1':>8}{'L2':>9}{'L3':>9}"
          f"{'saved':>9}{'drift':>8}{'MB(fp16)':>11}")
    rows = []
    for cap in CAPS:
        for pol in ("lru", "freshness"):
            m = bounded_run(records, stale, sim_age, cap, pol)
            fe = m["final_entries"]
            mb = (fe["l1"]*bpe["L1"] + fe["l2"]*bpe["L2"] + fe["l3"]*bpe["L3"]
                  + (fe["l1"]+fe["l2"])*EMBED_DIM*2) / MB
            m["mb_fp16"] = round(mb, 1)
            rows.append(m)
            print(f"  {str(cap or 'inf'):>8}{pol:>12}{m['l1_hits']:>8,}"
                  f"{m['l2_hits']:>9,}{m['l3_hits']:>9,}"
                  f"{m['search_saved_pct']:>8.1f}%{100*m['drift']:>7.2f}%"
                  f"{mb:>11.1f}")
    out["bounded"] = rows
    lsaved = 100 * (1 - locked["search_calls"] / locked["n_queries"])
    print(f"\n  unbounded reference (locked run): {lsaved:.1f}% saved at "
          f"{100*locked['cache_stale_error_rate']:.2f}% drift, "
          f"L1 {locked['l1_hits']:,} / L2 {locked['l2_hits']:,} / "
          f"L3 {locked['l3_hits']:,}")
    out["unbounded_locked"] = {"saved_pct": round(lsaved, 2),
                               "drift": locked["cache_stale_error_rate"],
                               "l1": locked["l1_hits"], "l2": locked["l2_hits"],
                               "l3": locked["l3_hits"]}

    (V8 / "deployment_cost_results.json").write_text(json.dumps(out, indent=2))
    print(f"\n  wrote {V8/'deployment_cost_results.json'}")


if __name__ == "__main__":
    main()
