#!/usr/bin/env python3
"""
TASK 2C -- blinded human annotation package for all 314 realised
L1-Precision pairs.

No model votes, no arm, no system identity, no similarity score is shown to
the annotator. Two independent forms (A and B) in DIFFERENT randomised orders,
plus an adjudication form for the cases where A and B disagree (generated by
make_adjudication.py after both come back).

NO LABEL IS FILLED BY ANY MODEL. The label column is empty by construction and
the integrity check verifies it stays empty.
"""
from __future__ import annotations
import csv, hashlib, json, pathlib, random

HERE = pathlib.Path(__file__).resolve().parent
LP = HERE.parents[1] / "l1_precision_gate"
SEED = 42

GUIDE = """# Human annotation — are these two questions asking the same thing?

You will see pairs of search questions. For each pair decide whether the two
questions **seek the same information**, so that a single correct answer could
reasonably serve both.

You are **not** judging whether the questions are worded similarly, whether
they are about the same topic, or whether any answer is correct. Only whether
the *requested information* is the same.

## The three labels

| label | use it when |
|---|---|
| `SAME` | the two questions seek the same information and can reasonably share one final answer |
| `DIFFERENT` | the requested information differs — even if the questions discuss the same entity or topic |
| `UNCERTAIN` | you cannot confidently determine equivalence |

Use `UNCERTAIN` sparingly, but do use it rather than guessing.

## Worked examples

**Different years / dates → DIFFERENT**
- A: "Who won the league in 2024?" B: "Who won the league in 2025?"
  → `DIFFERENT`. Same topic, different facts requested.

**Different numerical values → DIFFERENT**
- A: "What are the top 3 exports?" B: "What are the top 5 exports?"
  → `DIFFERENT`. The requested list size differs.

**Negation → DIFFERENT**
- A: "Which countries signed the treaty?" B: "Which countries did not sign the treaty?"
  → `DIFFERENT`. Opposite propositions.

**Comparative relations → DIFFERENT**
- A: "Which is the largest state by area?" B: "Which is the smallest state by area?"
  → `DIFFERENT`. Opposite relation.
- A: "Which is the largest state by area?" B: "Which state is it?"
  → `DIFFERENT`. One asks for a superlative, the other does not.

**Different entities → DIFFERENT**
- A: "What is the population of Austria?" B: "What is the population of Australia?"
  → `DIFFERENT`. Different entity.
- A: "iPhone 16 battery life" B: "iPhone 16 Pro battery life"
  → `DIFFERENT`. The second names a more specific product.

**Different answer types → DIFFERENT**
- A: "When was the bridge opened?" B: "Who designed the bridge?"
  → `DIFFERENT`. A date versus a person.

**Pure rewording → SAME**
- A: "Who is the CEO of the company?" B: "Who currently heads the company?"
  → `SAME`.
- A: "What colour is copper sulphate?" B: "What pigment does copper sulphate belong to?"
  → `SAME` if you judge that one answer serves both. This is the kind of
    borderline case where `UNCERTAIN` is legitimate.

**Formatting only → SAME**
- A: "Who won in 2024?" B: "Who won in year 2024?"
  → `SAME`.

## How to fill the file

Open your CSV (`human_annotation_A.csv` or `human_annotation_B.csv`) and put
exactly one of `SAME`, `DIFFERENT`, `UNCERTAIN` in the `human_label` column.
Leave `notes` blank unless something is worth flagging.

Do not consult the other annotator. Do not look at any model output. The rows
are deliberately in a different order in each file.

When both files are complete, run:

    python make_adjudication.py --a human_annotation_A.csv --b human_annotation_B.csv

and give the resulting `human_adjudication.csv` to a third person. Then run:

    python analyse_human_labels.py --a ... --b ... --adjudicated ...
"""


def h16(s):
    return hashlib.sha256((s or "").encode("utf-8")).hexdigest()[:16]


def main():
    rows = [r for r in csv.DictReader(
        open(LP / "heldout_l1_hits_judged.csv", encoding="utf-8"))
        if r["arm"] == "precision"]
    assert len(rows) == 314, f"expected 314 precision pairs, got {len(rows)}"
    items = []
    for r in rows:
        pid = f"{h16(r['incoming_query'])}_{h16(r['cached_query'])}"
        items.append({
            "pair_id": pid,
            "incoming_query": r["incoming_query"],
            "cached_query": r["cached_query"],
            "annotation_question": "Do these two questions seek the same "
                                   "information, such that one correct answer "
                                   "could reasonably serve both?",
            "human_label": "", "notes": ""})
    assert len({i["pair_id"] for i in items}) == len(items)

    for who, seed in (("A", SEED), ("B", SEED + 1)):
        s = items[:]
        random.Random(seed).shuffle(s)
        p = HERE / f"human_annotation_{who}.csv"
        with open(p, "w", newline="", encoding="utf-8") as fh:
            w = csv.DictWriter(fh, fieldnames=list(items[0]))
            w.writeheader(); w.writerows(s)
        print(f"  wrote {p.name}  ({len(s)} pairs, order seed {seed})")

    (HERE / "ANNOTATION_GUIDE.md").write_text(GUIDE, encoding="utf-8")
    json.dump({"n_pairs": len(items), "labels": ["SAME", "DIFFERENT", "UNCERTAIN"],
               "blinded": True,
               "shown_to_annotator": ["pair_id", "incoming_query",
                                      "cached_query", "annotation_question"],
               "withheld_from_annotator": ["model votes", "jury verdict",
                                           "policy/arm identity", "similarity",
                                           "Jaccard", "entities", "answer type",
                                           "guard outputs", "cached answer"],
               "annotators_required": 2, "adjudication_required": True,
               "labels_filled_by_model": 0,
               "status": "PENDING -- no human labels exist"},
              open(HERE / "human_package_manifest.json", "w"), indent=2)
    print(f"  wrote ANNOTATION_GUIDE.md, human_package_manifest.json")
    # integrity: the label column must be empty in both forms
    for who in ("A", "B"):
        rs = list(csv.DictReader(open(HERE / f"human_annotation_{who}.csv",
                                      encoding="utf-8")))
        filled = sum(1 for r in rs if r["human_label"].strip())
        assert filled == 0, f"form {who} has {filled} pre-filled labels"
    print(f"  INTEGRITY: both forms contain 0 filled labels. "
          f"Human verification is PENDING.")


if __name__ == "__main__":
    main()
